# url: http://kirbyt.github.io
# baseurl: /timeline-jekyll-theme

url: https://www.yumove.com.au/
# baseurl: /yumove

# Site Settings
title: YuMOVE Physiotherapy
description: "Yu Jia Su's landing page."
keywords: "jekyll, theme"
# google-tracking-id:

# Career Settings
# Default career thumbnail image.
# career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"]
